CLASS zfe_travel_001554_tc DEFINITION
 PUBLIC FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
ENDCLASS.

 CLASS zfe_travel_001554_tc IMPLEMENTATION.
 ENDCLASS.
